import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { LoginBtn } from "~/components/LoginBtn";

import { api } from "~/utils/api";

export default function Home() {
  const { data: session } = useSession();

  console.log(session);

  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const events = api.events.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {events?.data?.map((eventItem) => {
          return (
            <div className="text-black" key={eventItem.id}>
              {eventItem.title}
            </div>
          );
        })}

        <LoginBtn></LoginBtn>
      </main>
    </>
  );
}
